if(EXISTS "/Users/rustam/Documents/GitHub/istu_test_2024_2/tests/lr1_tests[1]_tests.cmake")
  include("/Users/rustam/Documents/GitHub/istu_test_2024_2/tests/lr1_tests[1]_tests.cmake")
else()
  add_test(lr1_tests_NOT_BUILT lr1_tests_NOT_BUILT)
endif()
