name: Cmake

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and run tests
        run: |
          cmake .
          cd bin
          cmake .. && make 
          ./tests/lr1_tests